import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')
const SRC = join(ROOT, 'src')

function jsStringEscape(raw) {
  return raw
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$/g, '\\$')
}

// Generate aria bundle
const ariaBundlePath = join(SRC, 'aria', 'aria-snapshot.bundle.txt')
const ariaContent = readFileSync(ariaBundlePath, 'utf-8')
const ariaTs = `// Generated by scripts/generate-assets.mjs — do not edit directly
export const ariaBundle: string = \`${jsStringEscape(ariaContent)}\`
`
writeFileSync(join(SRC, 'aria', 'aria-bundle.ts'), ariaTs)
console.log('Generated src/aria/aria-bundle.ts')

// Generate stealth patches
const stealthDir = join(SRC, 'stealth')
const files = readdirSync(stealthDir)
  .filter(f => f.endsWith('.txt'))
  .sort()

const patches = files.map(f => readFileSync(join(stealthDir, f), 'utf-8'))
const names = files.map(f => f.replace(/^\d+_stealth_/, '').replace('.txt', ''))

const patchesTs = `// Generated by scripts/generate-assets.mjs — do not edit directly
export const stealthPatches: string[] = [
${patches.map((p, i) => `  // ${files[i]}
  \`${jsStringEscape(p)}\``).join(',\n')}
]

export const stealthFileNames: string[] = [
${names.map(n => `  '${n}'`).join(',\n')}
]
`
writeFileSync(join(SRC, 'stealth', 'patches.ts'), patchesTs)
console.log('Generated src/stealth/patches.ts')
